emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    omit-unreachable-types: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/DiagnosticRP/{version-status}/{version}/diagnostic.json"
    examples-dir: "{project-root}/examples"
    arm-resource-flattening: true
  "@azure-tools/typespec-csharp":
    flavor: azure
    clear-output-folder: true
    namespace: "Azure.ResourceManager.Diagnostic"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
